# Generated by Django 4.1.7 on 2023-05-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_item_item_warnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
