# Generated by Django 4.1.7 on 2023-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('item', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=8)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='semester',
            field=models.CharField(choices=[('Zurhnii', 'Zurhnii'), ('Sahariin', 'Sahariin'), ('Horguijuuleh', 'Horguijuuleh'), ('Hoolbolovsruulah', 'Hoolbolovsruulah'), ('Tolgoin', 'Tolgoin'), ('Erchhvch', 'Erchhvch')], default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='./unicity_Logo.jpg', max_length=2000),
        ),
    ]
