# Generated by Django 4.1.7 on 2023-05-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_item_semester_alter_item_item_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='semester',
            new_name='item_type',
        ),
    ]
