# Generated by Django 4.1.7 on 2023-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_semester_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Zurhnii', 'Zurhnii'), ('Sahariin', 'Sahariin'), ('Horguijuuleh', 'Horguijuuleh'), ('Hoolbolovsruulah', 'Hoolbolovsruulah'), ('Tolgoin', 'Tolgoin'), ('Erchhvch', 'Erchhvch')], default='Zurhnii', max_length=200),
        ),
    ]
