# Generated by Django 4.1.7 on 2023-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Zurhnii', 'Zurhnii'), ('Turaah', 'Turaah'), ('Horguijuuleh', 'Horguijuuleh'), ('Hoolbolovsruulah', 'Hoolbolovsruulah'), ('Tolgoin', 'Tolgoin'), ('Erchhvch', 'Erchhvch'), ('Eregteichvvdiin', 'Eregteichvvdiin'), ('Emegteichvvdiin', 'Emegteichvvdiin'), ('Darhlaademjih', 'Darhlaademjih'), ('elegtsosnii', 'elegtsosnii')], default='Zurhnii', max_length=200),
        ),
    ]
